/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import Controller.Connect;
import Controller.TKMod;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmQLTK extends javax.swing.JFrame {

    /**
     * Creates new form frmQLTK
     */
    public frmQLTK() {
        initComponents();
        LoadCBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabTaoTK = new javax.swing.JTabbedPane();
        PnlTaoTK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDnv = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnXNTao = new javax.swing.JButton();
        btnQL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboMNV = new javax.swing.JComboBox<>();
        PnlXoaTK = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDx = new javax.swing.JTextField();
        txtMNVx = new javax.swing.JTextField();
        btnXNXoa = new javax.swing.JButton();
        btnEX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TÀI KHOẢN NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Nhập ID:");

        txtIDnv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Nhập Password:");

        btnXNTao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXNTao.setText("Xác Nhận");
        btnXNTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNTaoActionPerformed(evt);
            }
        });

        btnQL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQL.setText("Quay Lại");
        btnQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO TÀI KHOẢN");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setText("Chọn Mã Nhân Viên");

        cboMNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout PnlTaoTKLayout = new javax.swing.GroupLayout(PnlTaoTK);
        PnlTaoTK.setLayout(PnlTaoTKLayout);
        PnlTaoTKLayout.setHorizontalGroup(
            PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTaoTKLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDnv, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PnlTaoTKLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTaoTKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTaoTKLayout.createSequentialGroup()
                        .addComponent(btnXNTao)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTaoTKLayout.createSequentialGroup()
                        .addComponent(btnQL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        PnlTaoTKLayout.setVerticalGroup(
            PnlTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTaoTKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDnv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXNTao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        TabTaoTK.addTab("Tạo TK", PnlTaoTK);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("XÓA TÀI KHOẢN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("Nhập ID cần xóa:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Nhập mã nhân viên:");

        btnXNXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXNXoa.setText("Xác Nhận");
        btnXNXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNXoaActionPerformed(evt);
            }
        });

        btnEX.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEX.setText("Quay Lại");
        btnEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlXoaTKLayout = new javax.swing.GroupLayout(PnlXoaTK);
        PnlXoaTK.setLayout(PnlXoaTKLayout);
        PnlXoaTKLayout.setHorizontalGroup(
            PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlXoaTKLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlXoaTKLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlXoaTKLayout.createSequentialGroup()
                        .addGroup(PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMNVx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(txtIDx, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(113, 113, 113))))
            .addGroup(PnlXoaTKLayout.createSequentialGroup()
                .addGroup(PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlXoaTKLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnXNXoa))
                    .addGroup(PnlXoaTKLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnEX, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        PnlXoaTKLayout.setVerticalGroup(
            PnlXoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlXoaTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDx, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMNVx, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnXNXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        TabTaoTK.addTab("Xóa TK", PnlXoaTK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabTaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabTaoTK, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnQLActionPerformed

    private void btnXNTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNTaoActionPerformed
        // TODO add your handling code here:
        try
            {
                if (txtIDnv.getText() == "" || txtPass.getText() == "")
                {
                    JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin tài khoản!");
                    return;
                }

                if (txtIDnv.getText().length() != 10)
                {
                    JOptionPane.showMessageDialog(null,"Phải nhập đủ 10 ký tự cho ID đăng nhập!");
                    return;
                }
                if (txtPass.getText().length() < 6 || txtPass.getText().length() >15)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu phải có đồ dài từ 6-15 ký tự!");
                    return;
                }

                TKMod tk = new TKMod();
                if (tk.findTK(txtIDnv.getText()) == true)
                {
                    JOptionPane.showMessageDialog(null,"Tài khoản này đã tồn tại. Vui lòng nhập ID khác!");
                    return;
                }

                if (tk.findTK(txtIDnv.getText()) == false)
                {
                    tk.insert(txtIDnv.getText(), txtPass.getText(), cboMNV.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null,"Thêm Thành Công!");
                    txtIDnv.setText("");
                    txtPass.setText("");
                }
            }
            catch (Exception ex)
            {
            }
    }//GEN-LAST:event_btnXNTaoActionPerformed

    private void btnXNXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNXoaActionPerformed
        // TODO add your handling code here:
        try
            {
                if (txtIDx.getText().length() != 10 || txtMNVx.getText().length() != 10)
                {
                    JOptionPane.showMessageDialog(null,"Vui lòng nhập đủ 10 ký tự cho ID và MANV!");
                    return;
                }
                TKMod tk = new TKMod();
                if (tk.findTK(txtIDx.getText()) == false)
                {
                    JOptionPane.showMessageDialog(null,"Tài khoản không tồn tại. Vui lòng nhập ID khác!");
                    return;
                }
                if(txtMNVx.getText().equals(frmDangNhap.mnv))
                {
                    JOptionPane.showMessageDialog(null,"Không thể xóa tài khoản đang sử dụng!");
                    return;
                }
                if (tk.findTK(txtIDx.getText()) == true)
                {
                     int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa tài khoản này không?");
                     if (option == 0) {
                         tk.delete(txtIDx.getText(), txtMNVx.getText());
                         JOptionPane.showMessageDialog(null,"Xóa Thành Công!");
                         txtIDnv.setText("");
                         txtPass.setText("");
                     }
                }
            }
            catch (Exception ex)
            {
            }
    }//GEN-LAST:event_btnXNXoaActionPerformed

    private void btnEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnEXActionPerformed

    public void LoadCBO()
     {
         Connection connection = null;
        PreparedStatement statement = null;
        try {
            connection = Connect.getConnection();

            String sql = "SELECT distinct n.MANV FROM TAIKHOAN t, NHANVIEN n WHERE n.MANV not in (SELECT MANV FROM TAIKHOAN)";
            statement = connection.prepareCall(sql);
            ResultSet resultSet = statement.executeQuery();
            Vector data = new Vector();
            while (resultSet.next()) {
                data.add(resultSet.getString(1));
            }
            DefaultComboBoxModel cmbModel = new DefaultComboBoxModel(data);
            cboMNV.setModel(cmbModel);
        } catch (SQLException e) {
            Logger.getLogger(frmTrangChu.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frmTrangChu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    Logger.getLogger(frmTrangChu.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLTK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTaoTK;
    private javax.swing.JPanel PnlXoaTK;
    private javax.swing.JTabbedPane TabTaoTK;
    private javax.swing.JButton btnEX;
    private javax.swing.JButton btnQL;
    private javax.swing.JButton btnXNTao;
    private javax.swing.JButton btnXNXoa;
    private javax.swing.JComboBox<String> cboMNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtIDnv;
    private javax.swing.JTextField txtIDx;
    private javax.swing.JTextField txtMNVx;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
